🐛(npm) revert to yarn

diff --git a/.github/workflows/push_checking.yml b/.github/workflows/push_checking.yml
--- a/.github/workflows/push_checking.yml
+++ b/.github/workflows/push_checking.yml
@@ -18,11 +18,18 @@ jobs:
           node-version: ${{ matrix.node-version }}
 
       - name: Install dependencies
-        run: npm install
+
+        run: yarn install --frozen-lockfile
 
       - name: Lint sources
-        run: npm run lint
+        run: yarn run lint
 
+      - name: 'Check for uncommitted changes'
+        run: |
+          git diff --exit-code --stat -- . \
+          || (echo "##[error] found changed files after build. please 'yarn install --frozen-lockfile && yarn run lint:nofix && yarn run test:unit'" \
+                   "and check in all changes" \
+              && exit 1)
   unit_test:
     name: Unit tests
     runs-on: ubuntu-latest
@@ -40,10 +47,7 @@ jobs:
           node-version: ${{ matrix.node-version }}
 
       - name: Install dependencies
-        run: npm install
-
-      - name: Install Truffle
-        run: npm install -g truffle
+        run: yarn install --frozen-lockfile
 
       - name: Run tests
-        run: npm run test
+        run: yarn run test
