Docs/natspec (#56)
* ➕(doc) ItrustedIssuer

* ➕(natspec) added docs for claims and trustedissuers

* ➕(Identity) Natspec for Identity

* ➕(Identity) fix wrong doc

* 🐛(ClaimTopics) claimtopics set to private

* 🐛(IdentityRegistry) add doc for identity

* 🐛(push) fix push checking

* 🐛(push) fix push checking

Co-authored-by: Joachim <joachim@tokeny.com>

diff --git a/.github/workflows/push_checking.yml b/.github/workflows/push_checking.yml
--- a/.github/workflows/push_checking.yml
+++ b/.github/workflows/push_checking.yml
@@ -18,7 +18,8 @@ jobs:
           node-version: ${{ matrix.node-version }}
 
       - name: Install dependencies
-        run: yarn install
+
+        run: yarn install --frozen-lockfile
 
       - name: Lint sources
         run: yarn run lint
@@ -26,7 +27,7 @@ jobs:
       - name: 'Check for uncommitted changes'
         run: |
           git diff --exit-code --stat -- . \
-          || (echo "##[error] found changed files after build. please 'npm ci && npm run lint:nofix && npm run test:unit'" \
+          || (echo "##[error] found changed files after build. please 'yarn install --frozen-lockfile && yarn run lint:nofix && yarn run test:unit'" \
                    "and check in all changes" \
               && exit 1)
   unit_test:
@@ -46,7 +47,8 @@ jobs:
           node-version: ${{ matrix.node-version }}
 
       - name: Install dependencies
-        run: yarn install
+
+        run: yarn install --frozen-lockfile
 
       - name: Run tests
         run: yarn run test
